global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kafka-kraft"
    static_configs:
      - targets: ["kafka-kraft:9999"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb_exporter:9216"]

  - job_name: "kafka-connect"
    static_configs:
      - targets: ["kafka-connect:5083"]

  - job_name: "Atlas-mongo-metrics"
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: https
    basic_auth:
      username: user
      password: password
    http_sd_configs:
      - url: https://cloud.mongodb.com/prometheus/v1.0/groups/project_id/discovery
        refresh_interval: 60s
        basic_auth:
          username: user
          password: password
